name: Build Portable Image2VideoApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile --noconsole app.py

      - name: Package ZIP
        run: |
          mkdir dist_zip
          copy dist\app.exe dist_zip\
          powershell Compress-Archive -Path dist_zip\* -DestinationPath Image2VideoApp.zip

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: Image2VideoApp
          path: Image2VideoApp.zip
